services:
  catalog-service:
    build: .
    container_name: catalog-service-java
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-supabase}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE:-disable}
    restart: unless-stopped
